### ISSUE TITLE
APOD — API returns a Server Error 500 for lots of old APODs

### ISSUE THREAD

**Issue by rafaelderolez** [nasa/NASA-APIs#14]
The API returns an error for a considerate amount of dates. I've found this to be happening with mostly with dates before the year 2000 (it might occur for newer dates as well but haven't tested all dates). [Here's](https://api.nasa.gov/planetary/apod?date=1996-11-22&api_key=DEMO_KEY) an example of the error and [which APOD it should be returning](http://apod.nasa.gov/apod/ap961122.html).

`Request URL: https://api.nasa.gov/planetary/apod?date=1996-11-22&api_key=DEMO_KEY`
`Request Method:GET`
`Status Code:500 INTERNAL SERVER ERROR`

I was thinking of writing a script that tries to fetch all APODs until present day and have it output a list of those returning an error. If you have a better way to do this, let me know!

**Comment by martinsuchan** [comment]
I've created fetch script to check all days since the start of APOD on 20th June 1996 and found **530 missing days on server returning INTERNAL SERVER ERROR**.

The full list of days that return error is available here:
http://pastebin.com/fHDRN5Kw

**Comment by open768** [comment]
Worth talking to the pds operator. They Fixed A similar issue with the curiosity json feed. I think it was an aws issue

Sent from Yahoo Mail on Android 
 
  On Tue, 20 Sep, 2016 at 19:34, Martin Suchan<notifications@github.com> wrote:   
I've created fetch script to check all days since the start of APOD on 20th June 1996 and found 530 missing days on server returning INTERNAL SERVER ERROR.

The full list of days that return error is available here:
http://pastebin.com/fHDRN5Kw

**Comment by martinsuchan** [comment]
This issue is still not fixed. New date 2016/11/13 is now returning Status 500 for every request.
You can check it here:
https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&date=2016-11-13

**Comment by open768** [comment]
Hi have you contacted the pds  operator? 

Sent from Yahoo Mail on Android 
 
  On Sat, 3 Dec, 2016 at 11:17, Martin Suchan<notifications@github.com> wrote:   
This issue is still not fixed. New date 2016/11/13 is now returning Status 500 for every request.
You can check it here:
https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&date=2016-11-13

**Comment by martinsuchan** [comment]
@open768 I've tried reaching several people from PDS by email but without any response. The API is still returning 500 error for many days, it should be fixed, really.

**Comment by seanhardman** [comment]
Although the Planetary Data System (PDS) has been in discussion with the api.nasa.gov folks about adding access to our APIs, we have not yet completed this integration. The APOD site and its API are not under the purview of the PDS. If you haven't gotten a response through the Github repository, you might try contacting the APOD folks directly. By the way, I apologize for our Feedback form, although it threw an error, your request did make it to the PDS Operator.

**Comment by brianthomas** [comment]
Yes, the APOD API is currently maintained, at a very low level of effort, by our group not the PDS folks.

Our current thrust is to try to get approval to release the code/open source the API so that the community can help participate in maintaining the site.

Its regrettable that error 500 is being returned, and there may be a bug, or a good reason for this but I simply don’t have the time to investigate the issue right now.

Hopefully release of the code can happen soon.

Cheers,

=brian thomas


—
Brian Thomas, Ph.D.
OCIO Agency Data Scientist
Office of the Chief Information Officer
NASA Headquarters/2N29
300 E. Street SW
Washington, DC 20546
Office: 202 358 1580
Cell: 202 836 3364

**Comment by rafaelderolez** [comment]
Hey @brianthomas,

Thanks for bringing us up to speed. I haven't checked yet but there might be a common issue with those APODs returning an error. Maybe a character is throwing an error in the code, or maybe it's something bigger.

I guess we'll have to wait and see!

**Comment by jnbetancourt** [comment]
Updates to the APOD API have been made. I checked some of the broken dates and they're working now. Feel free to re-open this issue if you find other dates that are failing.

**Comment by petronny** [comment]
There are still 26 dates failing:
```
1996-01-07
1996-09-23
1996-10-02
2006-05-29
2007-05-22
2008-12-31
2009-04-05
2009-04-13
2009-06-29
2009-08-10
2010-01-20
2010-01-24
2010-05-10
2010-05-26
2010-06-08
2010-07-25
2010-08-25
2010-12-15
2011-01-23
2011-02-01
2011-02-22
2011-03-07
2012-03-12
2012-05-23
2014-01-12
2014-02-10
```

**Comment by html1011** [comment]
I am also receiving the same error from dates 2017-01-01 to 2017-12-31; however, it's working for dates in 2016.
